version: "3.3"

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        USER_ID: ${LOCAL_USER}
        GROUP_ID: ${LOCAL_USER}
    volumes:
    - .:/usr/src
    working_dir: /usr/src


